const products = [
    {
        userId: 1,
        id: 1,
        rating: 4.5,
        numReviews: 54,
        price: 1250,
        countInStock: 150,
        title: "sunt aut facere",
        body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    },
    {
        userId: 1,
        id: 2,
        rating: 5,
        numReviews: 234,
        price: 150,
        countInStock: 0,
        title: "qui est esse",
        body:
            "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
    },
    {
        userId: 1,
        id: 3,
        rating: 4,
        numReviews: 514,
        price: 1520,
        countInStock: 20,
        title: "ea molestias",
        body:
            "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
    },
    {
        userId: 1,
        id: 4,
        rating: 4,
        numReviews: 24,
        price: 1150,
        countInStock: 0,
        title: "eum et est occaecati",
        body:
            "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
    },
    {
        userId: 1,
        id: 5,
        rating: 3.6,
        numReviews: 22,
        price: 150,
        countInStock: 1050,
        title: "nesciunt quas odio",
        body: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
    },
    {
        userId: 1,
        id: 6,
        rating: 3,
        numReviews: 12,
        price: 150,
        countInStock: 0,
        title: "dolorem eum magni",
        body:
            "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
    },
    {
        userId: 1,
        id: 7,
        rating: 3.4,
        numReviews: 24,
        price: 1520,
        countInStock: 150,
        title: "magnam facilis autem",
        body: "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
    },
    {
        userId: 1,
        id: 8,
        rating: 4.7,
        price: 550,
        numReviews: 85,
        countInStock: 69,
        title: "dolorem dolore",
        body:
            "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
    },
    {
        userId: 1,
        id: 9,
        rating: 2,
        numReviews: 623,
        price: 190,
        countInStock: 420,
        title: "nesciunt iure omnis",
        body: "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas",
    },
    {
        userId: 1,
        id: 10,
        rating: 5,
        numReviews: 190,
        countInStock: 1250,
        price: 2000,
        title: "optio molestias",
        body: "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error",
    },
];

export default products;
